version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    docker:
        - image: mongo:4.2.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
workflows:
    build-and-test:
      jobs:
        - build-and-test